spring:
  datasource:
    druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TMall?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: qwe1728559437
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lyle.dmall.entity